-- ----------------------------
-- Table structure for CARD
-- ----------------------------
CREATE TABLE "CARD" (
"CARD_NO" VARCHAR2(32 BYTE) NOT NULL ,
"CARD_ID" VARCHAR2(33 BYTE) NULL ,
"CARD_NAME" VARCHAR2(30 BYTE) NULL ,
"CREDENTIALS_TYPE" VARCHAR2(20 BYTE) NULL ,
"CREDENTIALS_NO" VARCHAR2(18 BYTE) NULL ,
"CARD_TYPE" VARCHAR2(20 BYTE) NULL ,
"CARD_DATE" TIMESTAMP(6)  NULL ,
"PHONE" VARCHAR2(11 BYTE) NULL ,
"BANK" VARCHAR2(50 BYTE) NULL ,
"BACK_UP" VARCHAR2(4000 BYTE) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"LAST_STATUS" VARCHAR2(10 BYTE) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"DEPART" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "CARD"."CARD_NO" IS '卡编号,卡的编号，系统唯一识别';
COMMENT ON COLUMN "CARD"."CARD_ID" IS '卡号';
COMMENT ON COLUMN "CARD"."CARD_NAME" IS '持卡人姓名';
COMMENT ON COLUMN "CARD"."CREDENTIALS_TYPE" IS '持卡人证件类型';
COMMENT ON COLUMN "CARD"."CREDENTIALS_NO" IS '持卡人证件号';
COMMENT ON COLUMN "CARD"."CARD_TYPE" IS '卡类型';
COMMENT ON COLUMN "CARD"."CARD_DATE" IS '卡有效期';
COMMENT ON COLUMN "CARD"."BANK" IS '发卡行';
COMMENT ON COLUMN "CARD"."BACK_UP" IS '备用字段';
COMMENT ON COLUMN "CARD"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "CARD"."LAST_STATUS" IS '最后更新状态';
COMMENT ON COLUMN "CARD"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "CARD"."DEPART" IS '组织机构';

-- ----------------------------
-- Table structure for MERCHANT
-- ----------------------------
CREATE TABLE "MERCHANT" (
"CUSTOMER_NO" VARCHAR2(20 BYTE) NOT NULL ,
"CUSTOMER_ID" VARCHAR2(20 BYTE) NOT NULL ,
"CUSTOMER_LOGIN" VARCHAR2(21 BYTE) NULL ,
"CUSTOMER_NAME" VARCHAR2(50 BYTE) NULL ,
"CUSTOMER_BRIEFNAME" VARCHAR2(50 BYTE) NULL ,
"STATUS" VARCHAR2(10 BYTE) NULL ,
"DELETE_FLAG" VARCHAR2(10 BYTE) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"ACTIVE_TIME" TIMESTAMP(6)  NULL ,
"WITHDRAW_TIME" TIMESTAMP(6)  NULL ,
"CERTIFICATION_TIME" TIMESTAMP(6)  NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"CERTIFICATION_STATUS" VARCHAR2(10 BYTE) NULL ,
"ORIGINBACKOUTSTATE" VARCHAR2(10 BYTE) NULL ,
"CUST_TYPE" VARCHAR2(10 BYTE) NULL ,
"CUSTOMER_TYPE" VARCHAR2(10 BYTE) NULL ,
"MCC_ID" VARCHAR2(10 BYTE) NULL ,
"CONTRACT_NO" VARCHAR2(20 BYTE) NULL ,
"CONTRACT_DATE" TIMESTAMP(6)  NULL ,
"BUSINESS_ID" VARCHAR2(20 BYTE) NULL ,
"BUSINESS_TIME" TIMESTAMP(6)  NULL ,
"TAX_ID" VARCHAR2(20 BYTE) NULL ,
"TAX_NAME" VARCHAR2(20 BYTE) NULL ,
"TAX_DATE" TIMESTAMP(6)  NULL ,
"ORGANIZATION_ID" VARCHAR2(20 BYTE) NULL ,
"ORGANIZATION_DATE" TIMESTAMP(6)  NULL ,
"FINANCIAL_ADVISO" VARCHAR2(20 BYTE) NULL ,
"CORPORATE_NAME" VARCHAR2(20 BYTE) NULL ,
"CORPORATE_TYPE" VARCHAR2(10 BYTE) NULL ,
"CORPORATE_NO" VARCHAR2(20 BYTE) NULL ,
"CORPORATE_PHONE" VARCHAR2(11 BYTE) NULL ,
"CERTIFICATE_DATE" TIMESTAMP(6)  NULL ,
"COROPORATE_ADD" VARCHAR2(100 BYTE) NULL ,
"CONTACT" VARCHAR2(100 BYTE) NULL ,
"FAX" VARCHAR2(100 BYTE) NULL ,
"PHONE" VARCHAR2(20 BYTE) NULL ,
"CUSTOMER_ADD" VARCHAR2(100 BYTE) NULL ,
"EMAIL" VARCHAR2(30 BYTE) NULL ,
"POST_CODE" VARCHAR2(6 BYTE) NULL ,
"PROVINCE" VARCHAR2(30 BYTE) NULL ,
"CITY" VARCHAR2(20 BYTE) NULL ,
"BUSIS_COPE" VARCHAR2(10 BYTE) NULL ,
"MCHT_PROD_AREA" VARCHAR2(100 BYTE) NULL ,
"MCHT_PROD_REGION" VARCHAR2(100 BYTE) NULL ,
"INDUSTRY_TYPE" VARCHAR2(10 BYTE) NULL ,
"CREDIT_LEVEL" VARCHAR2(10 BYTE) NULL ,
"RISK_LEVEL" VARCHAR2(10 BYTE) NULL ,
"CUSTOMER_WEB" VARCHAR2(50 BYTE) NULL ,
"CUSTOMER_PROPERTY" VARCHAR2(10 BYTE) NULL ,
"REGISTERED_CAPITAL" VARCHAR2(10 BYTE) NULL ,
"LAND_USAGE" VARCHAR2(10 BYTE) NULL ,
"AREA" VARCHAR2(255 BYTE) NULL ,
"EMPLOYEE_NUM" VARCHAR2(10 BYTE) NULL ,
"STORE_NUM" NUMBER(6) NULL ,
"COMPANY_PROPERTY" VARCHAR2(30 BYTE) NULL ,
"CUSTOMER_SOURCE" VARCHAR2(30 BYTE) NULL ,
"MCC" VARCHAR2(20 BYTE) NULL ,
"TRADE_TYPE" VARCHAR2(10 BYTE) NULL ,
"PAY_WAY" VARCHAR2(10 BYTE) NULL ,
"ACCEPTANCE_WAY" VARCHAR2(10 BYTE) NULL ,
"OPEN_DATE" TIMESTAMP(6)  NULL ,
"ACQUIRER_EXPERIENCE" VARCHAR2(10 BYTE) NULL ,
"ACQUIRER_AGE" NUMBER(6) NULL ,
"DATE_SALEROOM" VARCHAR2(10 BYTE) NULL ,
"REFUSE" VARCHAR2(10 BYTE) NULL ,
"SETTLEMENT_TYPE" VARCHAR2(10 BYTE) NULL ,
"BANK_ACC_TYPE" VARCHAR2(10 BYTE) NULL ,
"BANK_CODE" VARCHAR2(10 BYTE) NULL ,
"OPENING_BANK" VARCHAR2(20 BYTE) NULL ,
"BANK_ID" VARCHAR2(20 BYTE) NULL ,
"BANK_PROVINCES" VARCHAR2(40 BYTE) NULL ,
"BANK_NAME" VARCHAR2(40 BYTE) NULL ,
"BANK_ADD" VARCHAR2(50 BYTE) NULL ,
"BACK_UP" VARCHAR2(4000 BYTE) NULL ,
"LAST_STATUS" VARCHAR2(10 BYTE) NULL ,
"DEPART" VARCHAR2(20 BYTE) NULL ,
"TOTAMT" VARCHAR2(255 BYTE) NULL ,
"TRMTYP" VARCHAR2(255 BYTE) NULL ,
"BRA_NAME" VARCHAR2(255 BYTE) NULL ,
"BRA_ADDRESS" VARCHAR2(255 BYTE) NULL ,
"BRA_ID" VARCHAR2(255 BYTE) NULL ,
"NETINST_ID" VARCHAR2(255 BYTE) NULL ,
"NETINST_NO" VARCHAR2(255 BYTE) NULL ,
"INST_ID" VARCHAR2(255 BYTE) NULL ,
"ORG_ID" VARCHAR2(200 BYTE) NULL ,
"COUNTRY_ID" VARCHAR2(200 BYTE) NULL ,
"SHARE_MODE" VARCHAR2(255 BYTE) NULL ,
"SERVICE_RATE" VARCHAR2(255 BYTE) NULL ,
"GUARANTEEMETHOD" VARCHAR2(255 BYTE) NULL ,
"ADDINGCATEGORY" VARCHAR2(255 BYTE) NULL ,
"WITHDRAWCATEGORY" VARCHAR2(255 BYTE) NULL ,
"PROPERTY_MEMBERINST_ID" VARCHAR2(200 BYTE) NULL ,
"ACQUIRERINSTNO" VARCHAR2(200 BYTE) NULL ,
"INNER_MCHNT_FLAG" VARCHAR2(255 BYTE) NULL ,
"CUPSFLAG" VARCHAR2(255 BYTE) NULL ,
"BUSSINESS_ACCEPT" VARCHAR2(255 BYTE) NULL ,
"DEVELOPINGMETHOD" VARCHAR2(255 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_NO" IS '商户序号';
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_ID" IS '商户号';
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_LOGIN" IS '商户登录号';
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_NAME" IS '商户全称';
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_BRIEFNAME" IS '商户简称';
COMMENT ON COLUMN "MERCHANT"."STATUS" IS '商户状态';
COMMENT ON COLUMN "MERCHANT"."DELETE_FLAG" IS '删除标记';
COMMENT ON COLUMN "MERCHANT"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MERCHANT"."ACTIVE_TIME" IS '激活时间';
COMMENT ON COLUMN "MERCHANT"."WITHDRAW_TIME" IS '撤销时间';
COMMENT ON COLUMN "MERCHANT"."CERTIFICATION_TIME" IS '实名认证时间';
COMMENT ON COLUMN "MERCHANT"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "MERCHANT"."CERTIFICATION_STATUS" IS '实名认证状态';
COMMENT ON COLUMN "MERCHANT"."ORIGINBACKOUTSTATE" IS '撤机前商户状态';
COMMENT ON COLUMN "MERCHANT"."CUST_TYPE" IS '商户客户类型';
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_TYPE" IS '商户类型';
COMMENT ON COLUMN "MERCHANT"."MCC_ID" IS '商户种类id';
COMMENT ON COLUMN "MERCHANT"."CONTRACT_NO" IS '协议编号';
COMMENT ON COLUMN "MERCHANT"."CONTRACT_DATE" IS '协议有效期';
COMMENT ON COLUMN "MERCHANT"."BUSINESS_ID" IS '营业执照号';
COMMENT ON COLUMN "MERCHANT"."BUSINESS_TIME" IS '营业执照有效期';
COMMENT ON COLUMN "MERCHANT"."TAX_ID" IS '税务登记证号';
COMMENT ON COLUMN "MERCHANT"."TAX_NAME" IS '税务登记名';
COMMENT ON COLUMN "MERCHANT"."TAX_DATE" IS '税务登记号有效期';
COMMENT ON COLUMN "MERCHANT"."ORGANIZATION_ID" IS '组织机构代码号';
COMMENT ON COLUMN "MERCHANT"."ORGANIZATION_DATE" IS '组织结构号到期时间';
COMMENT ON COLUMN "MERCHANT"."FINANCIAL_ADVISO" IS '财务联系人';
COMMENT ON COLUMN "MERCHANT"."CORPORATE_NAME" IS '法人姓名';
COMMENT ON COLUMN "MERCHANT"."CORPORATE_TYPE" IS '法人证件类型';
COMMENT ON COLUMN "MERCHANT"."CORPORATE_NO" IS '法人证件号码';
COMMENT ON COLUMN "MERCHANT"."CORPORATE_PHONE" IS '法人电话';
COMMENT ON COLUMN "MERCHANT"."CERTIFICATE_DATE" IS '证件有效期';
COMMENT ON COLUMN "MERCHANT"."COROPORATE_ADD" IS '法人地址';
COMMENT ON COLUMN "MERCHANT"."CONTACT" IS '商户联系人';
COMMENT ON COLUMN "MERCHANT"."FAX" IS '商户传真';
COMMENT ON COLUMN "MERCHANT"."PHONE" IS '商户联系电话';
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_ADD" IS '商户经营地址';
COMMENT ON COLUMN "MERCHANT"."EMAIL" IS '商户电子邮箱';
COMMENT ON COLUMN "MERCHANT"."POST_CODE" IS '邮编';
COMMENT ON COLUMN "MERCHANT"."PROVINCE" IS '所在省份';
COMMENT ON COLUMN "MERCHANT"."CITY" IS '所在城市';
COMMENT ON COLUMN "MERCHANT"."BUSIS_COPE" IS '经营范围';
COMMENT ON COLUMN "MERCHANT"."MCHT_PROD_AREA" IS '商户经营地段类型';
COMMENT ON COLUMN "MERCHANT"."MCHT_PROD_REGION" IS '商户经营地区类型';
COMMENT ON COLUMN "MERCHANT"."INDUSTRY_TYPE" IS '职业/行业类别';
COMMENT ON COLUMN "MERCHANT"."CREDIT_LEVEL" IS '信誉级别';
COMMENT ON COLUMN "MERCHANT"."RISK_LEVEL" IS '风险等级';
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_WEB" IS '商户网址';
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_PROPERTY" IS '商户性质';
COMMENT ON COLUMN "MERCHANT"."REGISTERED_CAPITAL" IS '注册资本';
COMMENT ON COLUMN "MERCHANT"."LAND_USAGE" IS '营业用地性质';
COMMENT ON COLUMN "MERCHANT"."AREA" IS '营业用地面积';
COMMENT ON COLUMN "MERCHANT"."EMPLOYEE_NUM" IS '员工数量';
COMMENT ON COLUMN "MERCHANT"."STORE_NUM" IS '连锁店数量';
COMMENT ON COLUMN "MERCHANT"."COMPANY_PROPERTY" IS '企业性质';
COMMENT ON COLUMN "MERCHANT"."CUSTOMER_SOURCE" IS '商户来源';
COMMENT ON COLUMN "MERCHANT"."MCC" IS 'MCC码';
COMMENT ON COLUMN "MERCHANT"."TRADE_TYPE" IS '商户交易类型';
COMMENT ON COLUMN "MERCHANT"."PAY_WAY" IS '商户付款方式';
COMMENT ON COLUMN "MERCHANT"."ACCEPTANCE_WAY" IS '商户受理方式';
COMMENT ON COLUMN "MERCHANT"."OPEN_DATE" IS '商户开业时间';
COMMENT ON COLUMN "MERCHANT"."ACQUIRER_EXPERIENCE" IS '收单经验';
COMMENT ON COLUMN "MERCHANT"."ACQUIRER_AGE" IS '收单年限';
COMMENT ON COLUMN "MERCHANT"."DATE_SALEROOM" IS '日预期销售额';
COMMENT ON COLUMN "MERCHANT"."REFUSE" IS '是否曾被拒';
COMMENT ON COLUMN "MERCHANT"."SETTLEMENT_TYPE" IS '商户结算类型';
COMMENT ON COLUMN "MERCHANT"."BANK_ACC_TYPE" IS '银行账号种类';
COMMENT ON COLUMN "MERCHANT"."BANK_CODE" IS '银行代码';
COMMENT ON COLUMN "MERCHANT"."OPENING_BANK" IS '开户银行';
COMMENT ON COLUMN "MERCHANT"."BANK_ID" IS '银行账号';
COMMENT ON COLUMN "MERCHANT"."BANK_PROVINCES" IS '银行所在省市';
COMMENT ON COLUMN "MERCHANT"."BANK_NAME" IS '开户支行名称';
COMMENT ON COLUMN "MERCHANT"."BANK_ADD" IS '开户行地址';
COMMENT ON COLUMN "MERCHANT"."BACK_UP" IS '备用字段';
COMMENT ON COLUMN "MERCHANT"."LAST_STATUS" IS '最后更新状态';
COMMENT ON COLUMN "MERCHANT"."DEPART" IS '联系部门号';
COMMENT ON COLUMN "MERCHANT"."TOTAMT" IS '押金服务费';
COMMENT ON COLUMN "MERCHANT"."TRMTYP" IS '机具类型';
COMMENT ON COLUMN "MERCHANT"."BRA_NAME" IS '网店名称';
COMMENT ON COLUMN "MERCHANT"."BRA_ADDRESS" IS '网点地址';
COMMENT ON COLUMN "MERCHANT"."BRA_ID" IS '网点ID';
COMMENT ON COLUMN "MERCHANT"."NETINST_ID" IS '网络接入服务商id';
COMMENT ON COLUMN "MERCHANT"."NETINST_NO" IS '网络接入服务商标号';
COMMENT ON COLUMN "MERCHANT"."INST_ID" IS '地市id';
COMMENT ON COLUMN "MERCHANT"."ORG_ID" IS '组织机构id';
COMMENT ON COLUMN "MERCHANT"."COUNTRY_ID" IS '区县id';
COMMENT ON COLUMN "MERCHANT"."SHARE_MODE" IS '参与分成方式';
COMMENT ON COLUMN "MERCHANT"."SERVICE_RATE" IS '服务等级';
COMMENT ON COLUMN "MERCHANT"."GUARANTEEMETHOD" IS '保证方式';
COMMENT ON COLUMN "MERCHANT"."ADDINGCATEGORY" IS '新增类别';
COMMENT ON COLUMN "MERCHANT"."WITHDRAWCATEGORY" IS '撤销类别';
COMMENT ON COLUMN "MERCHANT"."PROPERTY_MEMBERINST_ID" IS '商户权益方ID';
COMMENT ON COLUMN "MERCHANT"."CUPSFLAG" IS '银联总部接入标志';
COMMENT ON COLUMN "MERCHANT"."BUSSINESS_ACCEPT" IS '业务受理*';
COMMENT ON COLUMN "MERCHANT"."DEVELOPINGMETHOD" IS '拓展方式';

-- ----------------------------
-- Table structure for OPERATION
-- ----------------------------
CREATE TABLE "OPERATION" (
"ID" NUMBER(16) NOT NULL ,
"UUID" VARCHAR2(36 BYTE) NOT NULL ,
"OPER_NO" VARCHAR2(50 BYTE) NULL ,
"OPER_TYPE" VARCHAR2(20 BYTE) NOT NULL ,
"BIZ_CATE" VARCHAR2(10 BYTE) NULL ,
"OPER_TIME" TIMESTAMP(6)  NOT NULL ,
"OPER_STATUS" VARCHAR2(10 BYTE) NULL ,
"PAY_ID" VARCHAR2(20 BYTE) NULL ,
"USER_ID" VARCHAR2(20 BYTE) NULL ,
"USER_LOGIN" VARCHAR2(30 BYTE) NULL ,
"COL_CUST_ID" VARCHAR2(20 BYTE) NULL ,
"COL_CUST_NAME" VARCHAR2(50 BYTE) NULL ,
"PAY_AMT" NUMBER(16) DEFAULT 0  NULL ,
"PAY_TIME" TIMESTAMP(6)  NULL ,
"ACCOUNT_ID" VARCHAR2(20 BYTE) NULL ,
"BANK_ID" VARCHAR2(10 BYTE) NULL ,
"CARD_NO" VARCHAR2(20 BYTE) NULL ,
"PAY_MOD" VARCHAR2(11 BYTE) NULL ,
"RECHARGE_MOB" VARCHAR2(11 BYTE) NULL ,
"IP_ADDR" VARCHAR2(16 BYTE) NULL ,
"IP_PRV" VARCHAR2(20 BYTE) NULL ,
"IP_CITY" VARCHAR2(30 BYTE) NULL ,
"MAC" VARCHAR2(17 BYTE) NULL ,
"IMEI" VARCHAR2(15 BYTE) NULL ,
"MACHINE_ID" VARCHAR2(20 BYTE) NULL ,
"CPU_NO" VARCHAR2(20 BYTE) NULL ,
"DISK_NO" VARCHAR2(20 BYTE) NULL ,
"BROWSER_VER" VARCHAR2(10 BYTE) NULL ,
"BROWSER_TYPE" VARCHAR2(10 BYTE) NULL ,
"INPUT_VER" VARCHAR2(10 BYTE) NULL ,
"INPUT_TYPE" VARCHAR2(10 BYTE) NULL ,
"MACHINE_DACTYLOGRAM" VARCHAR2(20 BYTE) NULL ,
"OPER_PERSON" VARCHAR2(30 BYTE) NULL ,
"REMARK" VARCHAR2(100 BYTE) NULL ,
"EMAIL" VARCHAR2(50 BYTE) NULL ,
"CARD_TYPE" VARCHAR2(10 BYTE) NULL ,
"SN" VARCHAR2(30 BYTE) NULL ,
"OS" VARCHAR2(20 BYTE) NULL ,
"SIM" VARCHAR2(20 BYTE) NULL ,
"BANK_PHONE" VARCHAR2(11 BYTE) NULL ,
"BACK_UP" VARCHAR2(4000 BYTE) NULL ,
"BANK_ID_NO" VARCHAR2(20 BYTE) NULL ,
"ID_TYPE" VARCHAR2(10 BYTE) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"ID_NO" VARCHAR2(18 BYTE) NULL ,
"PHONE_NO" VARCHAR2(15 BYTE) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"LAST_STATUS" VARCHAR2(10 BYTE) NULL ,
"DEPART" VARCHAR2(20 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "OPERATION" IS '操作表';
COMMENT ON COLUMN "OPERATION"."ID" IS '操作流水号';
COMMENT ON COLUMN "OPERATION"."UUID" IS '操作唯一编号
';
COMMENT ON COLUMN "OPERATION"."OPER_NO" IS '操作编号(支付单保存)';
COMMENT ON COLUMN "OPERATION"."OPER_TYPE" IS '操作类型
';
COMMENT ON COLUMN "OPERATION"."BIZ_CATE" IS '业务组';
COMMENT ON COLUMN "OPERATION"."OPER_TIME" IS '操作时间
';
COMMENT ON COLUMN "OPERATION"."OPER_STATUS" IS '操作状态
';
COMMENT ON COLUMN "OPERATION"."PAY_ID" IS '支付标识
';
COMMENT ON COLUMN "OPERATION"."USER_ID" IS '用户号';
COMMENT ON COLUMN "OPERATION"."USER_LOGIN" IS '登录号';
COMMENT ON COLUMN "OPERATION"."COL_CUST_ID" IS '收款方标志
';
COMMENT ON COLUMN "OPERATION"."COL_CUST_NAME" IS '收款方名称
';
COMMENT ON COLUMN "OPERATION"."PAY_AMT" IS '支付金额
';
COMMENT ON COLUMN "OPERATION"."PAY_TIME" IS '支付时间
';
COMMENT ON COLUMN "OPERATION"."ACCOUNT_ID" IS '账户号
';
COMMENT ON COLUMN "OPERATION"."BANK_ID" IS '银行号';
COMMENT ON COLUMN "OPERATION"."CARD_NO" IS '银行卡号
';
COMMENT ON COLUMN "OPERATION"."PAY_MOD" IS '充值手机
';
COMMENT ON COLUMN "OPERATION"."RECHARGE_MOB" IS '被充值手机
';
COMMENT ON COLUMN "OPERATION"."IP_ADDR" IS 'IP地址';
COMMENT ON COLUMN "OPERATION"."IP_PRV" IS 'ip所在省';
COMMENT ON COLUMN "OPERATION"."IP_CITY" IS 'ip所在市';
COMMENT ON COLUMN "OPERATION"."MAC" IS 'mac地址';
COMMENT ON COLUMN "OPERATION"."IMEI" IS '手机串号';
COMMENT ON COLUMN "OPERATION"."MACHINE_ID" IS '终端编号';
COMMENT ON COLUMN "OPERATION"."CPU_NO" IS 'cpu编号';
COMMENT ON COLUMN "OPERATION"."DISK_NO" IS '硬盘编号';
COMMENT ON COLUMN "OPERATION"."BROWSER_VER" IS '浏览器版本';
COMMENT ON COLUMN "OPERATION"."BROWSER_TYPE" IS '浏览器类型';
COMMENT ON COLUMN "OPERATION"."INPUT_VER" IS '输入法版本';
COMMENT ON COLUMN "OPERATION"."INPUT_TYPE" IS '输入法类型';
COMMENT ON COLUMN "OPERATION"."MACHINE_DACTYLOGRAM" IS '机器指纹号
';
COMMENT ON COLUMN "OPERATION"."OPER_PERSON" IS '操作员';
COMMENT ON COLUMN "OPERATION"."REMARK" IS '备注';
COMMENT ON COLUMN "OPERATION"."EMAIL" IS '绑定邮箱
';
COMMENT ON COLUMN "OPERATION"."CARD_TYPE" IS '银行卡类型
';
COMMENT ON COLUMN "OPERATION"."SN" IS '手机序列号';
COMMENT ON COLUMN "OPERATION"."OS" IS '操作系统';
COMMENT ON COLUMN "OPERATION"."SIM" IS '手机SIM卡号
';
COMMENT ON COLUMN "OPERATION"."BANK_PHONE" IS '银行预留手机
';
COMMENT ON COLUMN "OPERATION"."BACK_UP" IS '备用字段';
COMMENT ON COLUMN "OPERATION"."BANK_ID_NO" IS '银行签约身份证
';
COMMENT ON COLUMN "OPERATION"."ID_TYPE" IS '证件类型';
COMMENT ON COLUMN "OPERATION"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "OPERATION"."ID_NO" IS '身份证号';
COMMENT ON COLUMN "OPERATION"."PHONE_NO" IS '电话号码';
COMMENT ON COLUMN "OPERATION"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "OPERATION"."LAST_STATUS" IS '最后更新状态';
COMMENT ON COLUMN "OPERATION"."DEPART" IS '所属组织机构';

-- ----------------------------
-- Table structure for PAY_ORDER
-- ----------------------------
CREATE TABLE "PAY_ORDER" (
"ORDER_ID" VARCHAR2(30 BYTE) NOT NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"REQUES_ID" VARCHAR2(10 BYTE) NULL ,
"TRANS_TIME" TIMESTAMP(6)  NULL ,
"TRANS_AMOUNT" NUMBER(18) NULL ,
"SUCC_AMOUNT" NUMBER(18) NULL ,
"CRY_TYPE" VARCHAR2(10 BYTE) NULL ,
"PAY_TYPE" VARCHAR2(10 BYTE) NULL ,
"STATUS" VARCHAR2(10 BYTE) NULL ,
"ORDER_CHNL" VARCHAR2(40 BYTE) NULL ,
"ORDER_TYPE" VARCHAR2(40 BYTE) NULL ,
"TRADE_MODE" VARCHAR2(10 BYTE) NULL ,
"TRADE_TYPE" VARCHAR2(10 BYTE) NULL ,
"ORDER_FROM" VARCHAR2(10 BYTE) NULL ,
"PAY_CUST_USER_ID" VARCHAR2(128 BYTE) NULL ,
"PAY_CUST_NAME" VARCHAR2(50 BYTE) NULL ,
"PAY_CUST_ACCT" VARCHAR2(20 BYTE) NULL ,
"PAY_CUST_CARD_NO" VARCHAR2(20 BYTE) NULL ,
"PAY_CUST_CARD_BIN" VARCHAR2(20 BYTE) NULL ,
"COL_CODE_IN" VARCHAR2(20 BYTE) NULL ,
"COL_CUST_USER_ID" VARCHAR2(20 BYTE) NULL ,
"COL_CUST_NAME" VARCHAR2(50 BYTE) NULL ,
"COL_CUST_ACCT" VARCHAR2(20 BYTE) NULL ,
"COL_CUST_CARD_NO" VARCHAR2(20 BYTE) NULL ,
"TRADE_NO" VARCHAR2(20 BYTE) NULL ,
"TARDE_NAME" VARCHAR2(50 BYTE) NULL ,
"EXT_ORDER_NO" VARCHAR2(20 BYTE) NULL ,
"FROZEN_AMOUNT" NUMBER(18) NULL ,
"FROZEN_TIME" TIMESTAMP(6)  NULL ,
"REFUND_TIME" TIMESTAMP(6)  NULL ,
"REFUND_AMOUNT" NUMBER(18) NULL ,
"REFUND_TIMES" NUMBER(18) NULL ,
"COMAMT" NUMBER(18) NULL ,
"OPER_NO" VARCHAR2(50 BYTE) NULL ,
"BACK_UP" VARCHAR2(4000 BYTE) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"LAST_STATUS" VARCHAR2(10 BYTE) NULL ,
"DEPART" VARCHAR2(20 BYTE) NULL ,
"POS_ID" VARCHAR2(30 BYTE) NULL ,
"IP_ADDR" VARCHAR2(50 BYTE) NULL ,
"MAC" VARCHAR2(30 BYTE) NULL ,
"SOURCE_LOCATION" VARCHAR2(128 BYTE) NULL ,
"CARD_CLASS" VARCHAR2(10 BYTE) NULL ,
"BUSS_CODE" VARCHAR2(20 BYTE) NULL ,
"CARD_CATE" VARCHAR2(20 BYTE) NULL ,
"CARD_BRAND_ID" VARCHAR2(20 BYTE) NULL ,
"ISS_INS_ID" VARCHAR2(20 BYTE) NULL ,
"ACQ_INS_ID_CD_IN" VARCHAR2(20 BYTE) NULL ,
"ACQ_INS_ID_CD_OUT" VARCHAR2(20 BYTE) NULL ,
"ACQ_AREA_CODE" VARCHAR2(20 BYTE) NULL ,
"CERTIF_TP" VARCHAR2(20 BYTE) NULL ,
"CERTIF_ID" VARCHAR2(20 BYTE) NULL ,
"CARD_HOLD_NAME" VARCHAR2(40 BYTE) NULL ,
"CARD_HOLD_SEX" VARCHAR2(20 BYTE) NULL ,
"DIAL_NUMBER" VARCHAR2(20 BYTE) NULL ,
"TRANS_PASSWORD" VARCHAR2(255 BYTE) NULL ,
"BANK" VARCHAR2(60 BYTE) NULL ,
"BANK_ACCOUNT" VARCHAR2(100 BYTE) NULL ,
"BANK_ACCOUNT_NAME" VARCHAR2(100 BYTE) NULL ,
"PAY_DETAIL" VARCHAR2(500 BYTE) NULL ,
"DATA_TYPE" VARCHAR2(60 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "PAY_ORDER" IS '支付单表';
COMMENT ON COLUMN "PAY_ORDER"."ORDER_ID" IS '订单号';
COMMENT ON COLUMN "PAY_ORDER"."CREATE_TIME" IS '订单创建时间
';
COMMENT ON COLUMN "PAY_ORDER"."REQUES_ID" IS '请求号
';
COMMENT ON COLUMN "PAY_ORDER"."TRANS_TIME" IS '交易时间
';
COMMENT ON COLUMN "PAY_ORDER"."TRANS_AMOUNT" IS '交易金额';
COMMENT ON COLUMN "PAY_ORDER"."SUCC_AMOUNT" IS '扣款金额';
COMMENT ON COLUMN "PAY_ORDER"."CRY_TYPE" IS '币种';
COMMENT ON COLUMN "PAY_ORDER"."PAY_TYPE" IS '支付类型';
COMMENT ON COLUMN "PAY_ORDER"."STATUS" IS '交易状态';
COMMENT ON COLUMN "PAY_ORDER"."ORDER_CHNL" IS '业务渠道';
COMMENT ON COLUMN "PAY_ORDER"."ORDER_TYPE" IS '订单类型';
COMMENT ON COLUMN "PAY_ORDER"."TRADE_MODE" IS '交易模式';
COMMENT ON COLUMN "PAY_ORDER"."TRADE_TYPE" IS '交易类型';
COMMENT ON COLUMN "PAY_ORDER"."ORDER_FROM" IS '订单来源';
COMMENT ON COLUMN "PAY_ORDER"."PAY_CUST_USER_ID" IS '支付方用户号';
COMMENT ON COLUMN "PAY_ORDER"."PAY_CUST_NAME" IS '支付方名称';
COMMENT ON COLUMN "PAY_ORDER"."PAY_CUST_ACCT" IS '支付方账号';
COMMENT ON COLUMN "PAY_ORDER"."PAY_CUST_CARD_NO" IS '支付卡号
';
COMMENT ON COLUMN "PAY_ORDER"."PAY_CUST_CARD_BIN" IS '卡bin';
COMMENT ON COLUMN "PAY_ORDER"."COL_CODE_IN" IS '商户类型';
COMMENT ON COLUMN "PAY_ORDER"."COL_CUST_USER_ID" IS '收款方用户号
';
COMMENT ON COLUMN "PAY_ORDER"."COL_CUST_NAME" IS '收款方名称';
COMMENT ON COLUMN "PAY_ORDER"."COL_CUST_ACCT" IS '收款方账号';
COMMENT ON COLUMN "PAY_ORDER"."COL_CUST_CARD_NO" IS '收款卡号
';
COMMENT ON COLUMN "PAY_ORDER"."TRADE_NO" IS '交易商品号';
COMMENT ON COLUMN "PAY_ORDER"."TARDE_NAME" IS '交易商品名称';
COMMENT ON COLUMN "PAY_ORDER"."EXT_ORDER_NO" IS '外部订单号
';
COMMENT ON COLUMN "PAY_ORDER"."FROZEN_AMOUNT" IS '冻结金额';
COMMENT ON COLUMN "PAY_ORDER"."FROZEN_TIME" IS '冻结时间';
COMMENT ON COLUMN "PAY_ORDER"."REFUND_TIME" IS '退款时间
';
COMMENT ON COLUMN "PAY_ORDER"."REFUND_AMOUNT" IS '退款金额';
COMMENT ON COLUMN "PAY_ORDER"."REFUND_TIMES" IS '退款次数
';
COMMENT ON COLUMN "PAY_ORDER"."COMAMT" IS '手续费';
COMMENT ON COLUMN "PAY_ORDER"."OPER_NO" IS '操作编号(付款方+收款方+时间+金额匹配)
';
COMMENT ON COLUMN "PAY_ORDER"."BACK_UP" IS '备用字段';
COMMENT ON COLUMN "PAY_ORDER"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "PAY_ORDER"."LAST_STATUS" IS '最后更新状态';
COMMENT ON COLUMN "PAY_ORDER"."DEPART" IS '所属组织机构';
COMMENT ON COLUMN "PAY_ORDER"."POS_ID" IS '终端编号';
COMMENT ON COLUMN "PAY_ORDER"."IP_ADDR" IS 'IP地址';
COMMENT ON COLUMN "PAY_ORDER"."MAC" IS 'mac地址';
COMMENT ON COLUMN "PAY_ORDER"."SOURCE_LOCATION" IS '客户端所在地区信息';
COMMENT ON COLUMN "PAY_ORDER"."CARD_CLASS" IS '卡种';
COMMENT ON COLUMN "PAY_ORDER"."BUSS_CODE" IS '业务代码';
COMMENT ON COLUMN "PAY_ORDER"."CARD_CATE" IS '卡类型';
COMMENT ON COLUMN "PAY_ORDER"."CARD_BRAND_ID" IS '卡品牌';
COMMENT ON COLUMN "PAY_ORDER"."ISS_INS_ID" IS '发卡机构';
COMMENT ON COLUMN "PAY_ORDER"."ACQ_INS_ID_CD_IN" IS '受理机构标识码(接收)';
COMMENT ON COLUMN "PAY_ORDER"."ACQ_INS_ID_CD_OUT" IS '受理机构标识码(发送)';
COMMENT ON COLUMN "PAY_ORDER"."ACQ_AREA_CODE" IS '受理地区代码
';
COMMENT ON COLUMN "PAY_ORDER"."CERTIF_TP" IS '证件类型';
COMMENT ON COLUMN "PAY_ORDER"."CERTIF_ID" IS '证件编号';
COMMENT ON COLUMN "PAY_ORDER"."CARD_HOLD_NAME" IS '持卡人姓名';
COMMENT ON COLUMN "PAY_ORDER"."CARD_HOLD_SEX" IS '持卡人性别
';
COMMENT ON COLUMN "PAY_ORDER"."DIAL_NUMBER" IS '电话号码
';
COMMENT ON COLUMN "PAY_ORDER"."TRANS_PASSWORD" IS '有无密码，有密：00
无密：01';
COMMENT ON COLUMN "PAY_ORDER"."BANK" IS '银行';
COMMENT ON COLUMN "PAY_ORDER"."BANK_ACCOUNT" IS '提现银行帐号';
COMMENT ON COLUMN "PAY_ORDER"."BANK_ACCOUNT_NAME" IS '银行开户帐户名';
COMMENT ON COLUMN "PAY_ORDER"."PAY_DETAIL" IS '支付明细';
COMMENT ON COLUMN "PAY_ORDER"."DATA_TYPE" IS '数据类型';

-- ----------------------------
-- Table structure for POS
-- ----------------------------
CREATE TABLE "POS" (
"POS_NO" VARCHAR2(20 BYTE) NOT NULL ,
"POS_ID" VARCHAR2(20 BYTE) NOT NULL ,
"SUBMCHNT_ID" VARCHAR2(32 BYTE) NULL ,
"CUSTOMER_NO" VARCHAR2(20 BYTE) NULL ,
"INST_ID" NUMBER(10) NULL ,
"TERM_ADDR" VARCHAR2(255 BYTE) NULL ,
"TERM_TEL" VARCHAR2(30 BYTE) NULL ,
"TERM_CONNMETHOD" NUMBER(1) NULL ,
"TERM_DIALPREFIX" VARCHAR2(10 BYTE) NULL ,
"TERM_DIALNO" VARCHAR2(30 CHAR) NULL ,
"LAST_STATUS" VARCHAR2(10 BYTE) NULL ,
"TERM_NATURE" VARCHAR2(50 BYTE) NULL ,
"POS_TYPE" VARCHAR2(10 BYTE) NULL ,
"TRADE_TYPE" VARCHAR2(10 BYTE) NULL ,
"TERMMODEL_ID" NUMBER(20) NULL ,
"TERM_VERSION" VARCHAR2(20 BYTE) NULL ,
"TERM_DEVELOPMAN" VARCHAR2(100 BYTE) NULL ,
"DELETE_FLAG" NUMBER(1) NULL ,
"PROPERTYSIDE" VARCHAR2(32 BYTE) NULL ,
"INCOMEMODE" NUMBER(5) NULL ,
"WITHDRAWCATE" VARCHAR2(5 BYTE) NULL ,
"PSAM_NO" VARCHAR2(16 BYTE) NULL ,
"REC_STATUS" VARCHAR2(10 BYTE) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"TERM_WITHDRAWDATE" TIMESTAMP(6)  NULL ,
"TERM_INSTALLDATE" TIMESTAMP(6)  NULL ,
"TERM_APPROVEDATE" TIMESTAMP(6)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "POS" IS 'pos机表';
COMMENT ON COLUMN "POS"."POS_NO" IS '终端续号';
COMMENT ON COLUMN "POS"."POS_ID" IS '终端编号
';
COMMENT ON COLUMN "POS"."SUBMCHNT_ID" IS '所属分店';
COMMENT ON COLUMN "POS"."CUSTOMER_NO" IS '所属商户';
COMMENT ON COLUMN "POS"."INST_ID" IS '所属机构';
COMMENT ON COLUMN "POS"."TERM_ADDR" IS '安装地点（柜台）';
COMMENT ON COLUMN "POS"."TERM_TEL" IS '柜台电话';
COMMENT ON COLUMN "POS"."TERM_CONNMETHOD" IS '接入方式';
COMMENT ON COLUMN "POS"."TERM_DIALPREFIX" IS '拨号前缀';
COMMENT ON COLUMN "POS"."TERM_DIALNO" IS '拨出电话';
COMMENT ON COLUMN "POS"."LAST_STATUS" IS '终端状态';
COMMENT ON COLUMN "POS"."TERM_NATURE" IS '终端性质';
COMMENT ON COLUMN "POS"."POS_TYPE" IS '终端连接类型';
COMMENT ON COLUMN "POS"."TRADE_TYPE" IS '交易类型';
COMMENT ON COLUMN "POS"."TERMMODEL_ID" IS '终端机型';
COMMENT ON COLUMN "POS"."TERM_VERSION" IS 'POS系统版本';
COMMENT ON COLUMN "POS"."TERM_DEVELOPMAN" IS '发展人';
COMMENT ON COLUMN "POS"."DELETE_FLAG" IS '删除标记';
COMMENT ON COLUMN "POS"."PROPERTYSIDE" IS '终端权益方';
COMMENT ON COLUMN "POS"."INCOMEMODE" IS '收益模式';
COMMENT ON COLUMN "POS"."WITHDRAWCATE" IS '撤销类别';
COMMENT ON COLUMN "POS"."PSAM_NO" IS '安全模块号';
COMMENT ON COLUMN "POS"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "POS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "POS"."TERM_WITHDRAWDATE" IS '撤销日期';
COMMENT ON COLUMN "POS"."TERM_INSTALLDATE" IS '现场安装日期';
COMMENT ON COLUMN "POS"."TERM_APPROVEDATE" IS '审核通过日期';

-- ----------------------------
-- Table structure for SIGNED
-- ----------------------------
CREATE TABLE "SIGNED" (
"PAY_CUST_ID" VARCHAR2(20 BYTE) NULL ,
"USER_NAME" VARCHAR2(20 BYTE) NULL ,
"ACCOUNT_ID" VARCHAR2(20 BYTE) NULL ,
"OPERS_ID" VARCHAR2(50 BYTE) NOT NULL ,
"STATUS" VARCHAR2(20 BYTE) NULL ,
"SIGNED_TIME" TIMESTAMP(6)  NULL ,
"CARD_NO" VARCHAR2(20 BYTE) NULL ,
"CARD_ACCOUNT_NAME" VARCHAR2(120 BYTE) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"LAST_STATUS" VARCHAR2(10 BYTE) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"DEPART" VARCHAR2(20 BYTE) NULL ,
"CARD_TYPE" VARCHAR2(10 BYTE) NULL ,
"BANK_ID" VARCHAR2(20 BYTE) NULL ,
"CERTIFICATE_TYPE" VARCHAR2(10 BYTE) NULL ,
"CERTIFICATE_NO" VARCHAR2(20 BYTE) NULL ,
"DAY_COUNT" NUMBER(4) NULL ,
"MAX_AMOUNT" NUMBER(10,2) NULL ,
"DAY_SUM_AMOUNT" NUMBER(10,2) NULL ,
"VALID_MONTH" VARCHAR2(2 BYTE) NULL ,
"VALID_YEAR" VARCHAR2(4 BYTE) NULL ,
"CREATE_IP" VARCHAR2(20 BYTE) NULL ,
"MOBILE_PHONE" VARCHAR2(20 BYTE) NULL ,
"PAY_GATE" VARCHAR2(32 BYTE) NULL ,
"BANK_CREATE_TIME" TIMESTAMP(6)  NULL ,
"CARD_FIRST_BIND_TIME" TIMESTAMP(6)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "SIGNED" IS '银行卡签约表';
COMMENT ON COLUMN "SIGNED"."PAY_CUST_ID" IS '付款方标志
';
COMMENT ON COLUMN "SIGNED"."USER_NAME" IS '用户号';
COMMENT ON COLUMN "SIGNED"."ACCOUNT_ID" IS '账户号
';
COMMENT ON COLUMN "SIGNED"."OPERS_ID" IS '操作编号';
COMMENT ON COLUMN "SIGNED"."STATUS" IS '签约状态
';
COMMENT ON COLUMN "SIGNED"."SIGNED_TIME" IS '签约时间
';
COMMENT ON COLUMN "SIGNED"."CARD_NO" IS '卡号
';
COMMENT ON COLUMN "SIGNED"."CARD_ACCOUNT_NAME" IS '持卡人姓名';
COMMENT ON COLUMN "SIGNED"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "SIGNED"."LAST_STATUS" IS '最后更新状态';
COMMENT ON COLUMN "SIGNED"."DEPART" IS '所属组织机构';
COMMENT ON COLUMN "SIGNED"."CARD_TYPE" IS '银行卡类型';
COMMENT ON COLUMN "SIGNED"."BANK_ID" IS '银行ID';
COMMENT ON COLUMN "SIGNED"."CERTIFICATE_TYPE" IS '身份种类';
COMMENT ON COLUMN "SIGNED"."CERTIFICATE_NO" IS '身份号码';
COMMENT ON COLUMN "SIGNED"."MAX_AMOUNT" IS '单笔最大金额';
COMMENT ON COLUMN "SIGNED"."DAY_SUM_AMOUNT" IS '日最高限额';
COMMENT ON COLUMN "SIGNED"."VALID_MONTH" IS '有效月';
COMMENT ON COLUMN "SIGNED"."VALID_YEAR" IS '有效年';
COMMENT ON COLUMN "SIGNED"."CREATE_IP" IS 'ip地址';
COMMENT ON COLUMN "SIGNED"."MOBILE_PHONE" IS '手机号码';
COMMENT ON COLUMN "SIGNED"."PAY_GATE" IS '支付网关';
COMMENT ON COLUMN "SIGNED"."BANK_CREATE_TIME" IS '银行端创建时间';
COMMENT ON COLUMN "SIGNED"."CARD_FIRST_BIND_TIME" IS '第一次绑定时间';

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
CREATE TABLE "USERS" (
"USER_ID" VARCHAR2(20 BYTE) NOT NULL ,
"ACCOUNT_ID" VARCHAR2(20 BYTE) NULL ,
"LOGIN_ID" VARCHAR2(20 BYTE) NULL ,
"USER_NAME" VARCHAR2(50 BYTE) NULL ,
"STATUS" VARCHAR2(10 BYTE) NULL ,
"SEX" VARCHAR2(10 BYTE) NULL ,
"BIRTHDAY" VARCHAR2(10 BYTE) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"ACTIVE_TIME" TIMESTAMP(6)  NULL ,
"REGISTER_TIME" TIMESTAMP(6)  NULL ,
"REGISTER_CITY" VARCHAR2(20 BYTE) NULL ,
"USER_TYPE" VARCHAR2(10 BYTE) NULL ,
"ACCOUNT_LEVEL" VARCHAR2(10 BYTE) NULL ,
"SAFE_LEVEL" VARCHAR2(10 BYTE) NULL ,
"CREDIT_LEVEL" VARCHAR2(10 BYTE) NULL ,
"INDUSTRY_TYPE" VARCHAR2(10 BYTE) NULL ,
"LINE_AUTHORITY" VARCHAR2(10 BYTE) NULL ,
"CERTIFICATE_TYPE" VARCHAR2(10 BYTE) NULL ,
"CERTIFICATE_NO" VARCHAR2(30 BYTE) NULL ,
"EXPIRY_DATE" TIMESTAMP(6)  NULL ,
"REGISTER_ADD" VARCHAR2(50 BYTE) NULL ,
"DEFAULT_ADD" VARCHAR2(100 BYTE) NULL ,
"SECURITY_TOOL" VARCHAR2(20 BYTE) NULL ,
"AUTH_TYPE" VARCHAR2(10 BYTE) NULL ,
"AUTH_STATUS" VARCHAR2(10 BYTE) NULL ,
"PHONE" VARCHAR2(40 BYTE) NULL ,
"EMAIL" VARCHAR2(50 BYTE) NULL ,
"RESERVED_INFO" VARCHAR2(30 BYTE) NULL ,
"QUESTION" VARCHAR2(30 BYTE) NULL ,
"ANSWER" VARCHAR2(30 BYTE) NULL ,
"PASSWORD_LESS" VARCHAR2(10 BYTE) NULL ,
"BACK_UP" VARCHAR2(4000 BYTE) NULL ,
"LAST_UPDATE_TIME" TIMESTAMP(6)  NULL ,
"LAST_STATUS" VARCHAR2(10 BYTE) NULL ,
"DEPART" VARCHAR2(100 BYTE) NULL ,
"SOURCE" VARCHAR2(100 BYTE) NULL ,
"BALANCE" VARCHAR2(100 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "USERS"."USER_ID" IS '用户编号';
COMMENT ON COLUMN "USERS"."ACCOUNT_ID" IS '账户号';
COMMENT ON COLUMN "USERS"."LOGIN_ID" IS '用户登陆号';
COMMENT ON COLUMN "USERS"."USER_NAME" IS '用户名';
COMMENT ON COLUMN "USERS"."STATUS" IS '状态';
COMMENT ON COLUMN "USERS"."SEX" IS '性别';
COMMENT ON COLUMN "USERS"."BIRTHDAY" IS '出生日期';
COMMENT ON COLUMN "USERS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "USERS"."ACTIVE_TIME" IS '激活时间';
COMMENT ON COLUMN "USERS"."REGISTER_TIME" IS '注册时间';
COMMENT ON COLUMN "USERS"."REGISTER_CITY" IS '注册城市';
COMMENT ON COLUMN "USERS"."USER_TYPE" IS '用户类型';
COMMENT ON COLUMN "USERS"."ACCOUNT_LEVEL" IS '账户级别';
COMMENT ON COLUMN "USERS"."SAFE_LEVEL" IS '安全等级';
COMMENT ON COLUMN "USERS"."CREDIT_LEVEL" IS '信誉级别';
COMMENT ON COLUMN "USERS"."INDUSTRY_TYPE" IS '职业/行业类别';
COMMENT ON COLUMN "USERS"."LINE_AUTHORITY" IS '业务权限';
COMMENT ON COLUMN "USERS"."CERTIFICATE_TYPE" IS '证件类型';
COMMENT ON COLUMN "USERS"."CERTIFICATE_NO" IS '证件号';
COMMENT ON COLUMN "USERS"."EXPIRY_DATE" IS '证件失效日期';
COMMENT ON COLUMN "USERS"."REGISTER_ADD" IS '注册地址';
COMMENT ON COLUMN "USERS"."DEFAULT_ADD" IS '默认收货地址';
COMMENT ON COLUMN "USERS"."SECURITY_TOOL" IS '安全工具';
COMMENT ON COLUMN "USERS"."AUTH_TYPE" IS '实名认证状态';
COMMENT ON COLUMN "USERS"."AUTH_STATUS" IS '数字证书状态';
COMMENT ON COLUMN "USERS"."PHONE" IS '绑定手机号';
COMMENT ON COLUMN "USERS"."EMAIL" IS '绑定邮箱';
COMMENT ON COLUMN "USERS"."RESERVED_INFO" IS '预留信息';
COMMENT ON COLUMN "USERS"."QUESTION" IS '安全问题';
COMMENT ON COLUMN "USERS"."ANSWER" IS '安全问题答案';
COMMENT ON COLUMN "USERS"."PASSWORD_LESS" IS '是否支持无密支付';
COMMENT ON COLUMN "USERS"."BACK_UP" IS '备用字段';
COMMENT ON COLUMN "USERS"."LAST_UPDATE_TIME" IS '最后更新时间';
COMMENT ON COLUMN "USERS"."LAST_STATUS" IS '最后更新状态';
COMMENT ON COLUMN "USERS"."DEPART" IS '部门号';
COMMENT ON COLUMN "USERS"."SOURCE" IS '开户来源';
COMMENT ON COLUMN "USERS"."BALANCE" IS '账户余额';

-- ----------------------------
-- Indexes structure for table CARD
-- ----------------------------

-- ----------------------------
-- Checks structure for table CARD
-- ----------------------------
ALTER TABLE "CARD" ADD CHECK ("CARD_NO" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table CARD
-- ----------------------------
ALTER TABLE "CARD" ADD PRIMARY KEY ("CARD_NO");

-- ----------------------------
-- Indexes structure for table MERCHANT
-- ----------------------------

-- ----------------------------
-- Uniques structure for table MERCHANT
-- ----------------------------
ALTER TABLE "MERCHANT" ADD UNIQUE ("CUSTOMER_ID");

-- ----------------------------
-- Checks structure for table MERCHANT
-- ----------------------------
ALTER TABLE "MERCHANT" ADD CHECK ("CUSTOMER_NO" IS NOT NULL);
ALTER TABLE "MERCHANT" ADD CHECK ("CUSTOMER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table MERCHANT
-- ----------------------------
ALTER TABLE "MERCHANT" ADD PRIMARY KEY ("CUSTOMER_NO");

-- ----------------------------
-- Indexes structure for table OPERATION
-- ----------------------------

-- ----------------------------
-- Checks structure for table OPERATION
-- ----------------------------
ALTER TABLE "OPERATION" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "OPERATION" ADD CHECK ("UUID" IS NOT NULL);
ALTER TABLE "OPERATION" ADD CHECK ("OPER_TYPE" IS NOT NULL);
ALTER TABLE "OPERATION" ADD CHECK ("OPER_TIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table OPERATION
-- ----------------------------
ALTER TABLE "OPERATION" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table PAY_ORDER
-- ----------------------------
CREATE INDEX "DS_TRANS_TIME"
ON "PAY_ORDER" ("TRANS_TIME" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table PAY_ORDER
-- ----------------------------
ALTER TABLE "PAY_ORDER" ADD CHECK ("ORDER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table PAY_ORDER
-- ----------------------------
ALTER TABLE "PAY_ORDER" ADD PRIMARY KEY ("ORDER_ID");

-- ----------------------------
-- Indexes structure for table POS
-- ----------------------------

-- ----------------------------
-- Checks structure for table POS
-- ----------------------------
ALTER TABLE "POS" ADD CHECK ("POS_ID" IS NOT NULL);
ALTER TABLE "POS" ADD CHECK ("POS_NO" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table POS
-- ----------------------------
ALTER TABLE "POS" ADD PRIMARY KEY ("POS_NO");

-- ----------------------------
-- Indexes structure for table SIGNED
-- ----------------------------

-- ----------------------------
-- Checks structure for table SIGNED
-- ----------------------------
ALTER TABLE "SIGNED" ADD CHECK ("OPERS_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SIGNED
-- ----------------------------
ALTER TABLE "SIGNED" ADD PRIMARY KEY ("OPERS_ID");

-- ----------------------------
-- Indexes structure for table USERS
-- ----------------------------

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "USERS" ADD CHECK ("USER_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "USERS" ADD PRIMARY KEY ("USER_ID");